version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Neet@s63
      MYSQL_DATABASE: todo_db
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    environment:
      - MYSQL_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
